services:
  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
    container_name: cloudsql-proxy
    platform: linux/amd64
    command: /cloud_sql_proxy glowing-sanctum-435218-h3:us-central1:weather-db-instance=tcp:5432
    ports: 
      - "5432:5432"
  app:
    build:
      context: .
    container_name: weather_app
    depends_on:
      - cloudsql-proxy
    env_file:
      - .env
    command: ["python", "main.py"]