version: '3.8'
services:
  app:
    build:
      context: .
    container_name: weather_app
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: weather_db
      POSTGRES_HOST: 127.0.0.1  # El host será localhost para el proxy
      POSTGRES_PORT: 5432        # Puerto estándar de PostgreSQL
    depends_on:
      - cloudsql-proxy
    command: ["python", "main.py"]

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
    container_name: cloudsql_proxy
    restart: always
    command: /cloud_sql_proxy -instances=glowing-sanctum-435218-h3:us-central1-c:weather-db-instance=tcp:5432
    volumes:
      - glowing-sanctum-435218-h3-0addde225723.json:/config  # Ruta a tu clave de servicio de cuenta
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/service-account-key.json

volumes:
  postgres_data:
    driver: local